### ISSUE TITLE
Meeting 1

### ISSUE THREAD

**Issue by DarthLlama** [dextermb/web-project#4]
# Agenda

- Discuss Skill sets and roles
- Decide on preliminary roles
- Discuss the company, and information we need to find out
- Discuss the software we'll use throughout the project

Pushed back to Friday.

**Comment by DarthLlama** [comment]
# Minutes

- Look into making an interactive map

**Comment by BradKollecker** [comment]
ask about Logo

**Comment by BradKollecker** [comment]
possible blog/ who maintains website/ how often do they wish to update

**Comment by dextermb** [comment]
# Present
- Alex
-Dexter
-Amanda
-Brady
